### ISSUE TITLE
General Newsfeed (Backend) - Routes to specific item page

### ISSUE THREAD

**Issue by samifaith** [Resilient-Labs/igotchu#11]

**Comment by AmandaMills-Hubbard** [comment]
//Routes for each individual post Ticket #11
`
app.get("/postedItem/:id", function(req, res) {
  let postedItemId = ObjectId(req.params.id)
  db.collection("postedItem").find({_id: postedItemId}).toArray((err, result) => {
`
`
    if (err) return console.log(err)
    res.render("postedItem.ejs", {
      postedItem: result,
      users : req.user
    })
  })
});
`
